### ISSUE TITLE
passing variable in the shortlink

### ISSUE THREAD

**Issue by therealelyayo** [JEduardoGD/ru.redirect#1]
would it be possible to append ?email=jackson@be.com to these redirect and then using the domain of the email to redirect somewhere ,
example?email=t@gmail.com would goto gmail.com

and t@yahoo.com shuld got yahoo.com

would that be possible

**Comment by JEduardoGD** [comment]
The short answer is: yes, it's possible.
Right now this project is a rest service that is ready for recive some string on this form: http://someserver/somestring, then   requests to database for the redirect value for somestring.
I mean, you should to have a database with the string-redirect pairs values to use successfully (check the tbl_req_redirect table on client/initdata/initdb.sql file).
If you want to go to the domain of some email address just need to change code to recive emails instead the **somestring** and split by the @ character to go to the url you want; or insert on database the explicit redirect url for some **somestring** but the number of emails string shuld be inserted manually one by one.

**Comment by therealelyayo** [comment]
damn i would need some serious help

**Comment by JEduardoGD** [comment]
Have you already woke up this project?
If so, I could add one more contoller so that you can receive email addresses so that when you receive /user@server.com you will be redirected to https://www.server.com; and when you receive /userb@cocacola.net send you to htts: //www.cocacola.net
